creation_rules:
# Encrypt data and stringData fields of Kubernetes Secret YAML files ending with .encrypted.yaml
- path_regex: \.encrypted\.yaml$
  encrypted_regex: ^(data|stringData)$
  # authenticating only the encrypted data allows updating metadata fields without re-encrypting
  mac_only_encrypted: true
  age: age1pvu03ch8cgm0eh8kc5wrpcpsgs3kqv765jmdqlj90nlgwx9avqzsjt0grd ##publickey

# Encrypt plain text files ending with .encrypted
- path_regex: \.encrypted$
  age: age1pvu03ch8cgm0eh8kc5wrpcpsgs3kqv765jmdqlj90nlgwx9avqzsjt0grd  ##publickey

stores:
  # Configure 2-space indentation for YAML files
  yaml:
    indent: 2
